### ISSUE TITLE
[Request] Audio improvements in Youtube Vanced

### ISSUE THREAD

**Issue by Kafu-Yukimura** [TeamVanced/Vanced#1143]
I requests disable loudness normalization before, but it was closed #367, so I'm requests it again.
And it requests for the option to hide the YouTube app update message.

Finally, I wish there was an option to force the sound quality option to AAC.
In the case of Opus, AAC 128Kbps upsampling to 256Kbps in most situations, and if you use 5G/4G LTE/3G or the Wi-Fi quality drops even a little, the sound quality will deteriorate.

EDIT: I am combining all audio related issues in one place so please refer to this issue for all such feature suggestions. Any duplicates or similar issues will be marked as duplicates from now on.
This includes:
- Disable loudness normalization
- Force to AAC Audio option
- Volume booster
- Equalizer
- Disable audio duck on notification
- Setting for pausing playback when other audio plays

**Comment by milindgoel15** [comment]
youtube controls the audio quality thru server

**Comment by Kafu-Yukimura** [comment]
@milindgoel15 Among the web browser third-party extensions, there are extensions that disable normalization, is there any way to disable it in a similar way to this?
Also, is there no way to force AAC 128k to load on the server?
It doesn't seem like YouTube has blocked AAC yet... (Only Opus is available for resolutions above WQHD.)
That is, is there no technical workaround? (I want to know if it is impossible because it is forced on the server.)

**Comment by milindgoel15** [comment]
YouTube on android ≠ YouTube on browsers

The extensions cannot work on mobile app because most of the YouTube code is written in protobuf and all encrypted codes and different kinds of calls. Xfile hasn't been much active in development these months due to his busy life. If it would be possible, it will come.

**Comment by Kafu-Yukimura** [comment]
I thought it was the same because it included SponsorBlock. I understand.
