### ISSUE TITLE
[Bug] Feed filter bar/tags below the header line not displayed on tablet

### ISSUE THREAD

**Issue by ghost** [TeamVanced/Vanced#1304]
**Bug description**
I just saw the feed filter tags mentioned on this thread: https://www.reddit.com/r/Vanced/comments/pxuez7/question_its_interesting_that_regular_youtube/
...like they are also available in the original YT app as well as the YT web version. But no matter what I tried, I can't activate them in YT Vanced version v16.29.39 on Android 9. I searched Reddit, XDA as well as the FAQ und the instructions, but couldn't find any hint how to activate these filter tags.
With the help of one Reddit community member I experienced the following:

When I reduce my dp size of my tablet (via developer options -> drawing -> smallest width) to 320, so that the Vanced Home screen is only displaying "one" column of videos, everything is fine and I can see the filter tag bar.
But if I increase the dp size to the actual dp size of my tablet (640) there are "two" columns of videos displayed at once on the YT Vanced Home screen. In this case, the filter tag bar is no longer visible / accessible.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 9 and Android 10

**Device**
HUAWEI Mediapad M5 10.8
as well as
Samsung Galaxy Tab A7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Stay on the home screen
3. Swipe down
4. No filter tag bar is displayed when the homescreen shows multiple columns of videos
5. Try the same thing on a phone or any device only able to display one column of videos and the filter tag bar will be displayed

**Expected behavior**
It is expected that the filter tag bar is also accessible for tablets

**Screenshots**
[https://imgur.com/a/596rouT](https://imgur.com/a/596rouT)

Reference to original reddit thread where the bug was discovered:
https://www.reddit.com/r/Vanced/comments/py2v3g/question_no_possibility_to_activate_the_feed/

**Comment by milindgoel15** [comment]
> like they are also available in the original YT app as well

You mean to say that the filter tags work fine on official YouTube when you use tablet dpi scale, but on vanced it bugs out?

**Comment by Vulpecula2020** [comment]
This is the impression I have. I installed the original YT app and
this is what I get: https://imgur.com/a/oow0EBf

**Comment by milindgoel15** [comment]
@Vulpecula2020  could u tell which original yt version you had while u were testing the issue?

**Comment by DraconicNEO** [comment]
This is an important issue, why is the wontfix tag automatically added to older issues?

**Comment by milindgoel15** [comment]
It could be an important issue from your perspective but not from our perspective. Our priorities are to bring ryd and some new stuff.

it doesn't mean that this won't get fixed, it will get fixed sooner or later. We are always keeping an eye on every issue on this repo so you don't need to worry anything about it at all. We just request you all to be patient.
