### ISSUE TITLE
[Bug] Issues with back on setting

### ISSUE THREAD

**Issue by YT-Advanced** [TeamVanced/Vanced#1626]
**Bug description:**
I have a problems with setting. When I go to setting then go to somethings like "Vanced Setting" and I click bac, It always go to the home page, not setting list.

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
Home page

**Android version:**
Android 10

**Device:**
Samsung Galaxy A20

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Go to setting, then choose one of them.
3. Next click back button on your screen.
4. If it go to the home page, not setting list, it is my problems I have.

**Comment by TheAmazingBen100** [comment]
Where did you download vanced from.
"Home Page" isn't a valid site.

**Comment by Hoang-Gia-Bao** [comment]
> Where did you download vanced from. "Home Page" isn't a valid site.

I download from Vanced Manager, and Home Page is the first page when you open the app bro

**Comment by milindgoel15** [comment]
That's now how you provide details of the source you downloaded vanced from. Yes, you are correct that you used vanced manager and installed vanced through the home page of that app.

But where did you got vanced manager from? That part was meant to be answered there.

**Comment by Hoang-Gia-Bao** [comment]
> That's now how you provide details of the source you downloaded vanced from. Yes, you are correct that you used vanced manager and installed vanced through the home page of that app.
> 
> But where did you got vanced manager from? That part was meant to be answered there.

I download from vancedapp.com bro

**Comment by milindgoel15** [comment]
Alright. Does your issue also happen on stock YouTube v17.03.38?

**Comment by Hoang-Gia-Bao** [comment]
> Alright. Does your issue also happen on stock YouTube v17.03.38?

I don't know because I am new on Vanced app. The first version I have used is v17.03.38

**Comment by milindgoel15** [comment]
> > Alright. Does your issue also happen on stock YouTube v17.03.38?
> 
> I don't know because I am new on Vanced app. The first version I have used is v17.03.38

Check the official YouTube App v17.03.38 if it has the same issue
