### ISSUE TITLE
[Bug] Next/previous track on headphones

### ISSUE THREAD

**Issue by CubergDev** [TeamVanced/Vanced#1629]
**Bug description:**
Can't control music with my headphones.

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
Used Github repository
**Android version:**
Android 12 (One UI 4)

**Device:**
Samsung Note 10+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Play any playlist
3. profit

**Expected behaviour:**
I should be able to do next/previous video or pause it with my FreeBuds Pro (2/3 click on headphones.Also music widget disappeared from lock screen. It happened after latest update. Before i was able to control music from headphones, and music widget appeared on lock screen

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._

**Comment by milindgoel15** [comment]
Try reinstalling vanced and perform a software upgrade of your headphones as well.

Also, check the same on stock yt 17.03.38

**Comment by CubergDev** [comment]
> Try reinstalling vanced and perform a software upgrade of your headphones as well.
> 
> Also, check the same on stock yt 17.03.38

Reinstalling doesn't help. Headphones software is up-to-date.
Solution for me: downgrade to 16.29.39 YT Vanced

**Comment by milindgoel15** [comment]
I don't think you checked on official YouTube app. Did you?

**Comment by CubergDev** [comment]
> I don't think you checked on official YouTube app. Did you?

How do i check it, if i dont have premium to enable background listening. This problem is related to background listening and PiP

**Comment by milindgoel15** [comment]
That you have to figure out how to check on official yt on your same device. Vanced only enables such features, it didn't invent them.

**Comment by KevinLane458** [comment]
I was having this same issue with v17.03.38 on my headphones and smart watch. What made it work for me was uninstalling Vanced, reinstalling v16.29.39, then upgrading to v17.03.38 again. This brought back play/pause and next/previous control on my headphones and smart watch, as well as brought back the lock screen widget.

Device: Samsung Galaxy S20 FE, Android 12 (OneUI 4.0)
Non-Root, downloaded via the Vanced Manager, downloaded from vancedapp.com
