### ISSUE TITLE
[Bug] Ads don't block in YouTube shorts

### ISSUE THREAD

**Issue by ech0devv** [TeamVanced/Vanced#1633]
**Bug description:**
In the YouTube shorts thing, when scrolling, ads can be encountered.

**Have you read vanced guides already? (YES/No)**
Yes. 

**Variant:**
Non-Root

**Vanced version:**
17.03.38
**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
Android 12

**Device:**
OnePlus 9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Shorts'
3. Scroll until ad is found.

**Expected behaviour:**
No ads at all.

**Comment by milindgoel15** [comment]
Try clearing cache or reinstallation. If the ad still appears, provide logcat while keeping debug mode enabled in vanced settings

**Comment by amarnathjamale** [comment]
Facing same issue. Tried clearing cache and reinstalling. Didn't helped.

**Comment by rakesh-krishna** [comment]
Variant:
Non-Root

Vanced version:
17.03.38
Link used to download vanced:
https://vancedapp.com/

Android version:
Android 11

Device:
Redmi note 10

Having same issue tried  clearing cache or reinstallation .
ad still appears

**Comment by milindgoel15** [comment]
Provide logcats as asked. The report you are sending ain't much helpful in fixing the ads in shorts.

**Comment by Winterfoxxy-0** [comment]
They no longer appear. The clearing cache seemed to fix it. Sorry for the inconvenience! I'll leave this open for anyone who still has the issue, and maybe they can provide logcats.

**Comment by rakesh-krishna** [comment]
[vancedLogCat.txt](https://github.com/YTVanced/Vanced/files/8101973/vancedLogCat.txt)

I have added logcat not sure if I have done it right 

steps I did (tell me if I am doing something worng)
 step 1 - closed all apps
 step 2- run "adb logcat > vancedLogCat.txt"
 step 3 - opened YTvanced ( I had enabled debug in settings)
 step 4 - started scrolling shorts until I reached an ad
 step 5 - stopped the command in cmd
 
 hope it helps

**Comment by Winterfoxxy-0** [comment]
They started appearing again, I'll provide logcats.

**Comment by Winterfoxxy-0** [comment]
Alright, above provided logcats. They started appearing again, however much less often.

**Comment by mkavinkumar1** [comment]
Bump
