### ISSUE TITLE
[Bug] Swiping backbutton after switching to landscape cause video to return vertical and requiring a second backswipe

### ISSUE THREAD

**Issue by BenjaminFraeyman** [TeamVanced/Vanced#1639]
**Bug description:**
Opening a video vertically, rotating to landscape and swiping to return causes it to first rotate vertically again

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-Root

**Vanced version:**
V17.03.38

**Link used to download vanced:**
Manager, dont remember where i got it before

**Android version:**
Android 11 

**Device:**
Oneplus 7 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on a video vertically
3. Rotate phone landscape
4.swipe to return -> video goes vertical
5. Swipe to return again -> app goes to feed vertically and immediately rotates landscape.

**Expected behaviour:**
On step 4 it goes to feed without going vertical first

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._

https://user-images.githubusercontent.com/24354378/154740321-7ed39906-dcc5-4a8b-9fcc-86e5fd6328ba.mp4

**Comment by milindgoel15** [comment]
Check this issue on official YouTube of same version as vanced (17.03.38)

Looks to us it's either stock yt bug or oos bug
