### ISSUE TITLE
[Bug] Captions preferences button does not contain relevant text

### ISSUE THREAD

**Issue by jectoric** [TeamVanced/Vanced#1649]
**Have you read vanced guides already?**
No

**Variant:**
Non-Root

**Vanced version:**
YouTube Vanced v17.03.38

**Link used to download vanced:**
Selected and downloaded latest version of YouTube from the Vanced manager

**Android version:**
Android 10

**Device:**
Xiaomi Redmi Note 7

**Precondition:**
Captions should be available for video

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Navigate to settings icon (right upper corner in player) > Captions
4. Observe result

**Expected behaviour:**
Bottom button should contain text 'Captions preferences'

**Actual result:**
Captions preferences button does not contain relevant text

![IMG_20220219_170245.jpg](https://user-images.githubusercontent.com/99994884/154806433-003e789f-688d-42ad-bca5-28b75557edd2.jpg)

**Comment by milindgoel15** [comment]
![Screenshot_2022-02-19-20-35-38-247_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/45682747/154806545-e8500c21-0dcf-424f-b1dd-7db102809e17.jpg)

Try basic troubleshooting
