### ISSUE TITLE
[Bug] Playback speed is reset to 1x after screen is unlocked

### ISSUE THREAD

**Issue by willindiana** [TeamVanced/Vanced#1662]
**Bug description:**
My default playback speed is 2x but if I lock my screen while watching a video, even if the video is paused when I unlock the video the playback speed is set back to 1x. This has started happening only on the latest update.

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-Root

**Vanced version:**
17.03.38 - Build 01.55.00

**Link used to download vanced:**
Vanced Manager

**Android version:**
Android 12 

**Device:**
Samsung Galaxy S21 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click play video at 2x speed
3. Keep video playing (or pause video)
4.  Lock Phone screen
5. Unlock Phone screen
6. Play Video or continue to play video and the speed will reset to 1x 

**Expected behaviour:**
I would expect the playback speed to continue at the set speed not reset to 1x.

Tag me to notify me if more details are needed.  Your work is appreciated and I have been loving the return of the dislike! Keep up the great work!

**Comment by milindgoel15** [comment]
Works fine here. Do basic troubleshooting to see if It helps.

**Comment by willindiana** [comment]
Hey there. I have taken some further troubleshooting tests. I removed the app and this fixed the issue for a short period before the speed reset started occurring again. I took a look at this issue https://github.com/YTVanced/Vanced/issues/1624 similar to mine and disabled sponsorblock in the settings and the issue is still present.

**Comment by milindgoel15** [comment]
I cannot reproduce this issue. Will ask our testers to check this.

**Comment by arseniiarsenii** [comment]
This bug also affects me. Playback speed also seems to reset to 1x after going into or exiting PiP mode and after locking the screen.

I'm on OnePlus 9R, Android 11. YouTube Vanced version is 17.03.38, SponsorBlock enabled, default playback speed is set to 1.5x, Premium account.

**Comment by dverma1232** [comment]
Same thing for me, I've tried reinstalling as well as disabling sponsor block

**Comment by spider3000** [comment]
I have the issue where playback speed resets to 1.0x too. I haven't figured out what is causing this tough, I always assumed it's mixing watching shorts with normal videos.

This issue has been going back to previous versions though.

**Comment by notsuhas** [comment]
Hey, I have the same issue and can replicate the same stated above. It's kinda annoying, but I'm putting up with it. Hope to see a fix in the next update. Glad that this problem is not just me, and now it's been referenced.
