### ISSUE TITLE
[Bug] Swipe controls are buggy in newer versions than 16.02.35

### ISSUE THREAD

**Issue by 313374** [TeamVanced/Vanced#1691]
Bug description:
Fast swipe from top to bottom in landscape mode for correcting brigthness and there is break (stopped at some value of brightness), u have to take your finger off and start over again - to correct. Last version where correct brightness swipe is 16.02.35, newer are bugged.

Have you read vanced guides already?
Yes.

Variant:
Non-Root.

Vanced version:
17.03.38

Link used to download vanced:
Selected and downloaded latest version of YouTube from the Vanced manager.

Android version:
Android 11 

Device:
Samsung Galaxy A52S

Steps to Reproduce
Steps to reproduce the error:
1. Open the app
2. Open random video
3. Turn to landscape mode
4. In 16.02.35 u can swipe back and forth on screen, there is no break. In newer versions, u fast swipe from top to bottom (repeating) and there is break (stopped at some value of brightness), u have to take your finger off and start over again - to correct.

Expected behaviour:
Work flawless, like in 16.02.35, smooth swiping to get correct brightness value without getting interruption.

**Comment by milindgoel15** [comment]
Provide more information on this. Screen record?

**Comment by milindgoel15** [comment]
Gotcha
