### ISSUE TITLE
[Bug] status bar going missing

### ISSUE THREAD

**Issue by clawyf** [TeamVanced/Vanced#1727]
**Bug description:**
Status bar and navbar hiding while in menus, it comes back only when watching shorts

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
v17.03.38

**Android version:**
Android 12

**Device:**
Google Pixel 6 Pro

**Steps to Reproduce**
I have no idea, it started in the comments of a shorts video

**Expected behaviour:**
Navbar would be visible when not in a video

![Screenshot_20220306-193105.png](https://user-images.githubusercontent.com/30278765/156958560-d9a549b3-d59b-4dc7-b0dd-ce8d58dbbd95.png)
![Screenshot_20220306-194029.png](https://user-images.githubusercontent.com/30278765/156958614-8a8eb79d-fb84-4e45-b24d-de3515650dcd.png)
Same page in youtube app working correctly

**Comment by milindgoel15** [comment]
Read https://github.com/YTVanced/Vanced/issues/1729#issuecomment-1060147779

**Comment by milindgoel15** [comment]
Missing steps to reproduce and how does the bug happen and bug report template not entirely followed
