### ISSUE TITLE
[Bug] Fullscreen videos not rendering right

### ISSUE THREAD

**Issue by clawyf** [TeamVanced/Vanced#1728]
**Bug description:**
Going into landscape mode often causes videos to be way off center and most of the screen is black

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
v17.03.38

**Android version:**
Android 12

**Device:**
Google Pixel 6 Pro

**Steps to Reproduce**
It seems to happen when reentering the app

**Expected behaviour:**
Fullscreen videos should always work normally

![Screenshot_20220220-000213.png](https://user-images.githubusercontent.com/30278765/156958864-1b9f9496-20c4-4629-976c-afd9f20426b8.png)
![Screenshot_20220304-152218.png](https://user-images.githubusercontent.com/30278765/156958872-ae070f99-2f7b-4937-a05f-4b6192da261c.png)

**Comment by milindgoel15** [comment]
Read https://github.com/YTVanced/Vanced/issues/1729#issuecomment-1060147779

**Comment by milindgoel15** [comment]
Missing proper steps to reproduce and how does the bug happen and bug report template not entirely followed
