### ISSUE TITLE
[Bug] Shorts Previous Video Rendering Into Next Video

### ISSUE THREAD

**Issue by NatsuDragneelHM** [TeamVanced/Vanced#1746]
**Bug description:**
While watching YouTube shorts occasionally the previously watched video will render partially into the next, I'm not sure why it happens but watching shorts occasionally leads to it

This will also occasionally happen to ordinary videos now, but it happens way more often in shorts

**Does your issue exists in the vanced guides? (YES/No)**
No

**Variant:**
non-root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk

(I downloaded via the manager I got from the official Vanced website at https://vancedapp.com/)

**Android version:**
Android 10

**Device:**
Samsung Galaxy A21 SM-S215DL

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
2. Click on a shorts video
3. Scroll through a few shorts videos
4. Scroll back up and start watching a short video

**Expected behaviour:**
Shorts videos should just play without rendering another video along with it, instead a previously seen short may appear with about two frames or so of it playing partially along with the new video you are watching

**Screen recording/screenshot of the bug:**
![Screenshot_20220311-171129](https://user-images.githubusercontent.com/49524383/157979486-7cd6331f-90ff-4647-866f-7f8e5590c43b.png)
![Screenshot_20220311-171134](https://user-images.githubusercontent.com/49524383/157979568-7390d29d-4ce8-48ac-a830-8c708b91e881.png)

**Comment by milindgoel15** [comment]
Check if it happens on stock YouTube 17.03.38

**Comment by NormalHuman-Anything** [comment]
Actually, this has happened for me on stock youtube app, so prob stock app error
