### ISSUE TITLE
[Question] Ressources about getting started on app modding

### ISSUE THREAD

**Issue by AkechiShiro** [TeamVanced/Vanced#1763]
**Ressources for app modding**
Could you please share any ressources about Android app modding ?

With Vanced's death, I think some users could give a try at taking the matter into their own hands.
It may be hard, not work or just takes months, but I'm willing to give it a try, got about 2 years probably until Vanced stops working.

**Comment by palexdev** [comment]
I agree with @AkechiShiro, you can't continue developing Vanced but maybe you can "teach/direct" someone in the modding world

**Comment by Systemad** [comment]
There are lots of guides and projects here on GitHub.
You'll need to know java, and have tools like Smali/baksmali, jadx, apktool, Frida.
