### ISSUE TITLE
Is there any chance of vanced coming back

### ISSUE THREAD

**Issue by Isssuemaker** [TeamVanced/Vanced#1764]
In this [Link](https://www.androidpolice.com/vanced-developers-issue-statement-addressing-wild-rumors-about-the-apps-demise/) 
It is said that vanced is closed due to new logo so if you remove new logo can vanced get back if not please state the reason

**Comment by RealKasumi** [comment]
Vanced has been discontinued because of cease and desist by Google. It's either Vanced is discontinued, or the owners get sued.
