### ISSUE TITLE
[Bug] VANCE VIDEO STARTS WITHOUT AUDIO PLAYBACK

### ISSUE THREAD

**Issue by Princele3** [TeamVanced/Vanced#1766]
VANCED AUDIO ISSUE

**Bug description:**
Everytime I try to start a video it starts without sound and I need to drag the cursor to restart does anyone know how I can fix this please

**Variant:**
Non root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
Vanced original link no longer works

**Android version:**
Android 12

**Device:**
Xiaomi redmi note 10 pro

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
2. Click on play video
3. Video starts without audio then I need to start it over

**Expected behaviour:**
Video starts with proper audio

**Comment by milindgoel15** [comment]
Issue with the OS.
