### ISSUE TITLE
[Bug] Something wrong with the screen (glitch)

### ISSUE THREAD

**Issue by EsterMew** [TeamVanced/Vanced#1767]
**Bug description:**
Sometimes when i play some video, my screen become like this (see the video I've uploaded), that bug happens frequently, i need to close my yt vanced and open it again to remove that glitch screen, but it didn't always work.

**Does your issue exists in the vanced guides? (YES/No)**
No, I've been searching but didn't find the same issue

**Variant:**
Non-root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
https://youtubevanced.com/

**Android version:**
Android 11 

**Device:**
Oppo F11

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
2. Click on the video you want to watch
3. and the bug happen

**Expected behaviour:**
That glitch shouldn't happen, i expect to watch clean video on my screen

**Screen recording/screenshot of the bug:**
https://drive.google.com/file/d/1gj2_p0i-FYnBxEjd5svaKla3pa9DvvON/view?usp=drivesdk

Here my screen record

_Attach logcats in case of crashes by uploading them to pastebin or katbin if possible. These can help solve the issue._

> 

Ah okay, thank. I'll delete this thread

**Comment by RealKasumi** [comment]
known bug with some devices on this version, downgrade to 16.29

**Comment by EsterMew** [comment]
> known bug with some devices on this version, downgrade to 16.29

Ah okay, thanks, I'll delete this thread
