### ISSUE TITLE
[Bug] my youtube vanced gives me the error [400] and the pages not working pls resolve this bug

### ISSUE THREAD

**Issue by Olly1234572882** [TeamVanced/Vanced#1769]
**Bug description:**
Replace here with a clear and detailed description of the bug. Keep the description as short as possible

**Does your issue exists in the vanced guides? (YES/No)**
If your answer is yes, please consider re-reading before creating any issue. The guides can be found in the readme section of this repository. Else follow this template when creating issue

**Variant:**
Replace here the variant you are using, i.e., non-root or root

**Vanced version:**
Replace here with the exact version of YouTube Vanced you are using. It is mandatory to report issues from the latest available versions only as old versions are deprecated and no longer supported. For example, v17.03.38

**Link used to download vanced:**
Replace here with the source/link you used to download and install on your device. 

**Android version:**
Replace here with the version of Android your device have. For example, Android 11 

**Device:**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behaviour:**
Replace here with a description of what you expected should happen and what happened instead.

**Screen recording/screenshot of the bug:**
Replace here with the screenshot of the bug or provide screen recording for proper debugging.

_Attach logcats in case of crashes by uploading them to pastebin or katbin if possible. These can help solve the issue._

**Comment by milindgoel15** [comment]
V14 is deprecated by Google. Update to latest YouTube
