### ISSUE TITLE
[Idea] replaceme

### ISSUE THREAD

**Issue by UsernameXXXXXXXX** [TeamVanced/Vanced#1770]
Hello, i'm currently using the last version of YT Vanced but 2 days ago I was on the 14.21.54 version (not working now error 400), in this version I always had in the first page the music playlists create by YT with the songs that I listen and new songs that I can like too, In the current version I can't find these playlists,  Is it possible to make these mix playlists come back in the first page ? That's only with these playlists that i found new songs x) 
**Description**
Replace me with a clear and detailed description of the idea.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
The content that is displayed on the home tab is controlled by Google. Ask them
