### ISSUE TITLE
Fuck Google

### ISSUE THREAD

**Issue by leodoi3** [TeamVanced/Vanced#1771]

**Comment by RealKasumi** [comment]
Don't blame Google for the Vanced shutdown, Vanced were clearly in the wrong for providing an ad free and modified version of mobile yt.
Vanced was going to get the kick in the ass at some point, we all knew it was going to happen, the main question was when it was going to happen.

Please only use this issue repo for genuine issues or possible suggestions. Go rant about giant corporations elsewhere.

**Comment by peepopoggers** [comment]
@RealKasumi They were not in the wrong, free software :P
