### ISSUE TITLE
[Idea] The age verification pass. Somewhere in Settings. I can't watch some YouTube videos because they were put on Age restricted for a stupid reason

### ISSUE THREAD

**Issue by GabrielCND** [TeamVanced/Vanced#1772]
**Description**
Replace me with a clear and detailed description of the idea.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Ask Google. Vanced is discontinued and there will be no updates anymore.
