### ISSUE TITLE
[Bug] No proper shading on pause in specific cases

### ISSUE THREAD

**Issue by ComValer** [TeamVanced/Vanced#1787]
**Bug description:**
Here's a bug that appears on video pause with specific ways. It lies in the fact it then just not being shaded.

**Does your issue exists in the vanced guides? (YES/No)**
No

**Variant:**
both root and non-root version

**Vanced version:**
v17.03.38

**Link used to download vanced:**
from Vanced Manager

**Android version:**
Android 11

**Device:**
Realme 8i, but is discovered on the others (Xiaomi Mi A2 Lite, Huawei P8, Lenovo IdeaPad S145 (w Bliss OS 11) - it's in an app layouts itself💀 awy

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
2. Start video
3. Pause it via pressing "Space", "MEDIA_PLAY_PAUSE" keys, or return to the activity when it is paused - you'll get the same pause, but with no video shading

**Expected behaviour:**
Video should be shaded.

**Screen recording/screenshot of the bug:**
That's how it supposed to look (👌👌✌️)
![Screenshot_20220730-234932](https://user-images.githubusercontent.com/72487083/181995946-73638a33-4d14-4fa0-973b-283f23c2152e.jpg)

And that's how it actually does 😑😑 (in cases with reproduced steps.)
![Screenshot_20220730-234925](https://user-images.githubusercontent.com/72487083/181995952-3a18456f-f013-49d4-904f-5b6a0301c33d.jpg)

it distracts a lot and is overall unaesthetical and bad-looking. please fix it

**Comment by milindgoel15** [comment]
Ask Google now
