### ISSUE TITLE
[Bug] Physical keyboard keys are not mapped properly

### ISSUE THREAD

**Issue by ComValer** [TeamVanced/Vanced#1788]
**Bug description:**
Pressing the keyboard keys may act differently depending on the taken context, but it's taken wrong during the video playback. Also there some cases it's just not working so see in the bug report details.

**Does your issue exists in the vanced guides? (YES/No)**
No

**Variant:**
root and non-root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
from Vanced Manager

**Android version:**
Android 11, Android 7, Android 9

**Device:**
Realme 8i, Huawei P8, Lenovo IdeaPad S145 (with Bliss OS 11)

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
1.2 When focused on video thumbnail (via physical keyboard key "ARROW" or any other), no key is working as it's playback initiator (while the "Enter" key activates The Others element function)

2.2 Start watching any video (to start a playback mode)
2.3 Pressing the key "Space" is working in a wrong context (if it's not a fullscreen video playback), but it moves focus to the activity elements, not working as a Keyboard Shortcut (list is available when holding "Ctrl" key).
![Screenshot_20220731-184408](https://user-images.githubusercontent.com/72487083/182034316-d5648acd-a3d0-40d2-835a-825c67242027.jpg)
(That's what it does in the case instead.: .it focuses on the first element, But It doesn't Play/Pause vid (like it should in the case))

**Expected behaviour:**
1.2 When focused on video thumbnail, key "Enter" should start it's playback, but it's not
2.3 Key "Space" should Play/Pause video all the time if the video playback mode is On (video is chosen and playable)

**Comment by milindgoel15** [comment]
Ask Google now
