### ISSUE TITLE
[Bug] cant install vanced music

### ISSUE THREAD

**Issue by Kk12hh** [TeamVanced/Vanced#1789]
**Bug description:**
Replace here with a clear and detailed description of the bug. Keep the description as short as possible
Cant install vanced music in Korea Android Galaxy Note 10

**Does your issue exists in the vanced guides? (YES/No)**
If your answer is yes, please consider re-reading before creating any issue. The guides can be found in the readme section of this repository. Else follow this template when creating issueY

**Variant:**
Replace here the variant you are using, i.e., non-root or root
NON ROOTED
**Vanced version:**
Replace here with the exact version of YouTube Vanced you are using. It is mandatory to report issues from the latest available versions only as old versions are deprecated and no longer supported. For example, v17.03.38

4.64.51

**Link used to download vanced:**
Replace here with the source/link you used to download and install on your device. 

Vanced.app

**Android version:**
Replace here with the version of Android your device have. For example, Android 11 

ANDROID 12
**Device:**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8
SAMSUNG GALAXY NOTE 10 / ANDROID / KOREA
**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
3. ....

Tried to install in vanced manager and then few seconds error occurs. Check the screen shot

**Expected behaviour:**
Replace here with a description of what you expected should happen and what happened instead.
Use vanced music
**Screen recording/screenshot of the bug:**
Replace here with the screenshot of the bug or provide screen recording for proper debugging.
![Uploading Screenshot_20220807-194300_Vanced Manager.jpg…]()

++ ) 
The error says
INSTALL_PHRASE_FAILED_NOT_APK:Failed to phrase/data/app/vmdl1822339722.tmp/install: Failed to load asset path /data/app/1822339722.tmp/install

_Attach logcats in case of crashes by uploading them to pastebin or katbin if possible. These can help solve the issue._

**Comment by milindgoel15** [comment]
Read troubleshooting guides
