### ISSUE TITLE
[Idea] remove shorts video from vanced

### ISSUE THREAD

**Issue by Orbitalstrike99** [TeamVanced/Vanced#1790]
add a function that let users to block or remove youtube short video from vanced app, from all pages like home pages and subscription, many people hated this "short" tictok kind of video including me, so a function that let user remove all shorts video or able to block video below certain length (ie. 30 sec or 60 sec) would be awesome

**Comment by milindgoel15** [comment]
Ask Google now

**Comment by Orbitalstrike99** [comment]
wdym ask Google, you think I didn't do research beforehand as this has been
bugging me for 2 years now? its not possible in original app and it sure
isn't possible in vanced, which is why I'm requesting this feature

**Comment by EatVanced** [comment]
Do more research, ask google for this

**Comment by Orbitalstrike99** [comment]
stop saying use Google, if you are so sure there are solutions, show me
then, cos I'm sure there isn't, that's exactly why I'm requesting this
feature, is this how you guys treat feedbacks? use Google?

**Comment by milindgoel15** [comment]
FOR YOUR INFORMATION, VANCED HAD BEEN DISCONTINUED IN MARCH. 

Meaning there will be no more future updates of any kind. So please tell Google to fulfill your wishes now.

**Comment by Orbitalstrike99** [comment]
huh, I thought you guys just left Google play store since conflict with
their guideline and continue on github and sideloader, my bad

**Comment by Radplay** [comment]
Vanced never was in the Play store to begin with lol
