### ISSUE TITLE
[Idea] Age Verification Remover addon to application

### ISSUE THREAD

**Issue by michelle1574** [TeamVanced/Vanced#1791]
**Description**
I found it somewhere on internet and it works. If you have one added, ignore this.
Link to source code: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/
I'm not sure if this can be converted into a integration.
They said that have a userscript.

An describing image link: https://user-images.githubusercontent.com/59258980/133007022-c12253c0-036c-49fe-8fce-42b62da14e8a.png

**Comment by milindgoel15** [comment]
Ask Google. Vanced is no longer in operation.

**Comment by michelle1574** [comment]
> Ask Google. Vanced is no longer in operation.

Do you thing I'm about to watch this shittish YouTube made by Sroogle?! No, you better fuck it up!

**Comment by milindgoel15** [comment]
You better start reading things. Go on and search the internet about vanced discontinuation. Might as well read the readme of this repository as well.
