### ISSUE TITLE
Offline 

### ISSUE THREAD

**Issue by kdg00** [TeamVanced/Vanced#1793]
Miui 13.0.3 
Xiaomi Redmi Note 10 5G
 i tried redownload but it didn't help
![Screenshot_2022-09-25-20-57-57-847_com vanced android youtube](https://user-images.githubusercontent.com/83062418/192161120-4542c241-bec2-4e5f-8985-f22638fde8a7.jpg)

**Comment by milindgoel15** [comment]
Duplicate of #786
