### ISSUE TITLE
[Bug] vanced force me to update the youtube 

### ISSUE THREAD

**Issue by LauSan00** [TeamVanced/Vanced#1794]
Hi I encounter a problem with youtube vanced latest version, I use a phone without gms, everything worked ok until I did a reset to all the settings in the phone. 
Now I can no longer see any video with the old google account, just on incognito mode and short videos. If I use a vpn it only works on certain countries. 
 I reinstalled the application I deleted the data I reintroduced the problematic account and nimi
We have added one more new account and on it everything works perfectly. 
![Screenshot_20221006_161442_com vanced android youtube](https://user-images.githubusercontent.com/115498445/194933726-17990f57-ff67-4c4d-8668-1b50fb421dac.jpg)

**Comment by milindgoel15** [comment]
Blame Google. We can't do anything.
