### ISSUE TITLE
[Question] Is there anyway to make yt vanced disguised as yt official

### ISSUE THREAD

**Issue by putrawahh** [TeamVanced/Vanced#1800]
There is an issue with chrome regarding the search result which produce youtube links which can only be opened by official yt app or chrome itself. That issue is also mentioned in this post.

https://github.com/TeamVanced/Vanced/issues/296#issuecomment-1310258256

but there is close tag on that issue so i post new one. Thank you team vanced you are the best!

**Comment by milindgoel15** [comment]
There's no better way to disguise vanced as stock YouTube other than installing the root version.
Many android skins offer their ways to set default apps and some are effective but some are barely working. You can check out the guide in the readme section of this repository for your skin. 

Fully disguised and working solution will be the root version only.

**Comment by TURB042O** [comment]
> There is an issue with chrome regarding the search result which produce youtube links which can only be opened by official yt app or chrome itself. That issue is also mentioned in this post.
> 
> [#296 (comment)](https://github.com/TeamVanced/Vanced/issues/296#issuecomment-1310258256)
> 
> but there is close tag on that issue so i post new one. Thank you team vanced you are the best!

if you're meaning official as in using assistant to control it. then yes there is.:
![SmartSelect_20221123_041257_Google](https://user-images.githubusercontent.com/90441459/203521226-f9bf5574-47ef-4790-8fb3-f52d6337ed59.jpg)
![Screenshot_20221123_041308_Google](https://user-images.githubusercontent.com/90441459/203521231-8b6dbe21-43e4-495f-bb53-d99162f270cc.png)

goto music settings and select no provider, then uninstall play store's YT music, and personally I disable the play store's YouTube since I use revanced for that.

**Comment by TURB042O** [comment]
> There's no better way to disguise vanced as stock YouTube other than installing the root version. Many android skins offer their ways to set default apps and some are effective but some are barely working. You can check out the guide in the readme section of this repository for your skin.
> 
> Fully disguised and working solution will be the root version only.

I'm not non-rooted and found a way easily. hope this helps

**Comment by milindgoel15** [comment]
It does work for assistants to play music and all but not the YouTube app when opening yt links from other apps.

**Comment by milindgoel15** [comment]
It differs from skin to skin like i said in the first post.

**Comment by TURB042O** [comment]
> It differs from skin to skin like i said in the first post. Some do it better, some are worse.

what do you mean by skin to skin?

**Comment by milindgoel15** [comment]
> > It differs from skin to skin like i said in the first post. Some do it better, some are worse.
> 
> what do you mean by skin to skin? 

Skins are MIUI, oneUI, colorOS, etc. Anything which is not in the form of AOSP is called custom android skin for their brands.
