### ISSUE TITLE
[Bug]Hello! I have a wierd problem when i go in the history video section i see video that i don't even know about let alone watch.All seam to have in common thinks about cracking apps or using hack 

### ISSUE THREAD

**Issue by 4DAVID7** [TeamVanced/Vanced#1801]
**Bug description:**
Replace here with a clear and detailed description of the bug. Keep the description as short as possible

**Does your issue exists in the vanced guides? (YES/No)**
If your answer is yes, please consider re-reading before creating any issue. The guides can be found in the readme section of this repository. Else follow this template when creating issue

**Variant:**
Replace here the variant you are using, i.e., non-root or root

**Vanced version:**
Replace here with the exact version of YouTube Vanced you are using. It is mandatory to report issues from the latest available versions only as old versions are deprecated and no longer supported. For example, v17.03.38

**Link used to download vanced:**
Replace here with the source/link you used to download and install on your device. 

**Android version:**
Replace here with the version of Android your device have. For example, Android 11 

**Device:**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behaviour:**
Replace here with a description of what you expected should happen and what happened instead.

**Screen recording/screenshot of the bug:**
Replace here with the screenshot of the bug or provide screen recording for proper debugging.

_Attach logcats in case of crashes by uploading them to pastebin or katbin if possible. These can help solve the issue._

**Comment by milindgoel15** [comment]
History only shows videos that get played by any device which has your account signed in. And this has nothing to do with the vanced or YouTube app.

**Comment by 4DAVID7** [comment]
Thanks for your replye ,you are right i am sorry for the misunderstanding.
.After i have done a security check and log out of all my devices the
problem disappeared.

sâm., 19 nov. 2022, 17:13 Milind Goel ***@***.***> a scris:
