### ISSUE TITLE
[Idea] Release only the source code that was added-in/edited for Vanced (YT) 

### ISSUE THREAD

**Issue by Daasin** [TeamVanced/Vanced#1802]
**Description**
To atleast release just the source code that was added-in/edited for Vanced (YT) by itself in an archive as stated in the title could be archived either for educational purposes or for personal usage only, and possibly even allowed to get new patches.
but preferably under a FOSS License like GPLv3

**Comment by Daasin** [comment]
That way, not all the work would have to go to waste and could be helpful to other FOSS Projects one way or another without using Youtube/Googles code

**Comment by Daasin** [comment]
That way, not all the work would have to go to waste and could be helpful to other FOSS Projects one way or another without using Youtube/Googles code @Vendicated @VancedOfficial 
 
Surely something worth reconsidering, right?  
  
  
 ‍⁠  ﻿ ﻿‍ ‍⁠ 


 
 ﻿‍ ﻿‍⁠ ﻿‍ ﻿‍⁠⁠‍⁠  ﻿ ‍⁠  ﻿ ﻿‍

**Comment by milindgoel15** [comment]
Nope

**Comment by Daasin** [comment]
> Nope

Ah, I see. Thank you for the response in any case :3
