### ISSUE TITLE
[Bug] contents not loaded

### ISSUE THREAD

**Issue by tibdev78** [TeamVanced/Vanced#1805]
Hi,
Since today I try to get the content but instead I have the screen offline whereas when I browse the web it works.

![Screenshot_2022-12-23-18-16-24-85_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/40746565/209375898-86346343-fc8c-4f8f-8aa0-638b8192dad1.jpg)

**Comment by milindgoel15** [comment]
Read the troubleshooting from the readme section of this repo
