### ISSUE TITLE
[Bug] don't work vanced microG

### ISSUE THREAD

**Issue by mrstargate** [TeamVanced/Vanced#1806]
**Bug description:**
I have installed vanced manager from the website,after i have installed first microG and at last vanced 
I opened vanced i click for insert the account but after i click login...microG crashed 
I have all version updated.

**Does your issue exists in the vanced guides?
 No**

**Variant:**
Non root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
https://youtubevanced.com/

**Android version:**
Android 12

**Device:**
Samsung Galaxy A13

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app vanced
3. Click login
4. click login (in microG)
5. crash.

**Expected behaviour:**
Insert my account google and look my videos 

**Screen recording/screenshot of the bug:**
![Screenshot_20221225-224639_Device care](https://user-images.githubusercontent.com/63281425/209482732-feae3d36-1562-4203-bddd-253d8f7b5200.jpg)
(Yes i'm italian)

_Attach logcats in case of crashes by uploading them to pastebin or katbin if possible. These can help solve the issue._
?

**Comment by milindgoel15** [comment]
Usage of unofficial website.

**Comment by mrstargate** [comment]
hi,
i look the official site https://vancedapp.com/ but i read:
Vanced no Longer Available, instead:
What does it mean?
if is possible could you have the apk file for my phone which i would like
to vanced because the website haven't the file
*PariTopo(PariSimone)*


Il giorno mar 27 dic 2022 alle ore 10:53 Milind Goel <
***@***.***> ha scritto:

**Comment by milindgoel15** [comment]
Yes, because vanced had been discontinued. Please read the readme of this repository.

As for apk file, we cannot share any download links anymore. Ask a friend or use apkmirror

**Comment by mrstargate** [comment]
i don't know apkmirror what is that?
*PariTopo(PariSimone)*


Il giorno mar 27 dic 2022 alle ore 16:39 Milind Goel <
***@***.***> ha scritto:

**Comment by milindgoel15** [comment]
Google it please

**Comment by mrstargate** [comment]
Thanks, I will.
*PariTopo(PariSimone)*


Il giorno mar 27 dic 2022 alle ore 16:45 Milind Goel <
***@***.***> ha scritto:
