### ISSUE TITLE
[Idea]  dual-subtitles

### ISSUE THREAD

**Issue by imhosooo** [TeamVanced/Vanced#1807]
I'm asking for a dual-subtitles. Dual-subtitles is a technology that uses languages from different countries to watch them at once, showing two kinds of language on one screen. This technology extracts two caption sources and sends them to the screen as subtitles. Dual-subtitles is still a technology that can only be used on computers. However, Vanced has the ability to expand this. Please. IT would be vary helpful if you add it.

I wnat to learn another country's language with mobile YouTube.

Link to technology like this is ' https://chrome.google.com/webstore/detail/youtube-dual-subtitles/hkbdddpiemdeibjoknnofflfgbgnebcm '
You can see the detailed usage , technology and images on the link

Sorry,  I am not good at English, so I don't know how to express my earnstness.....

**Comment by milindgoel15** [comment]
Ask Google now.
