### ISSUE TITLE
[Idea] Is it possible to disable shorts scrolling up or down?

### ISSUE THREAD

**Issue by Viom888** [TeamVanced/Vanced#1810]
**Description**
Can we have shorts scrolling feature disable option?
It will help a lot to get out of bad addiction of shorts.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment]
Ask Google now

**Comment by Viom888** [comment]
Isn't it possible?

**Comment by milindgoel15** [comment]
Who knows? 

We have stopped development for vanced. Please read the readme portion of this repository before making new issues? Yea
