### ISSUE TITLE
[Bug] Shorts video closing on clicking replies.

### ISSUE THREAD

**Issue by KartikSindura** [TeamVanced/Vanced#1811]
**Bug description:**
Clicking "view reply" button on any shorts videos closes it.

**Does your issue exists in the vanced guides? (YES/No)**
No

**Variant:**
Non-root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
https://youtubevanced.com/

**Android version:**
Android 12

**Device:**
Motorola G82 5G

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
2. Click on a shorts video 
3. Click on comments
4. Find a comment with replies
5. Click on view replies

**Expected behaviour:**
Should open the replies and the video should remain in the background, instead the replies open up on the home screen and the video closes.

**Screen recording/screenshot of the bug:**
https://drive.google.com/file/d/19b9dAAJS95Lui8uuRq_1iN2Do5A2kgIT/view?usp=drivesdk

**Comment by milindgoel15** [comment]
Vanced is no longer maintained. Please read readme before creating issues
