### ISSUE TITLE
[Bug] YouTube Music Vanced infinite crash

### ISSUE THREAD

**Issue by melhorAmigolegal** [TeamVanced/Vanced#1812]
**Bug description:**
When I open the rooted version of YouTube Music Vanced It crashes, then the logo chances, and when I re-open It crashes again

**Does your issue exists in the vanced guides? (YES/No)**
No

**Variant:**
root

**Vanced version:**
4.64.51

**Link used to download vanced:**
https://youtubevanced.com/

**Android version:**
Android 10

**Device:**
Motorola Moto G7 Play

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
2. Open the app again

**Expected behaviour:**
I expected to work, but didn't worked

**Screen recording/screenshot of the bug:**

https://drive.google.com/file/d/11EHnTNPe3mph0dF2iYF0-x4ZVr3xO83i/view?usp=drivesdk

_Attach logcats in case of crashes by uploading them to pastebin or katbin if possible. These can help solve the issue._

**Comment by milindgoel15** [comment]
Please read the readme of this repo. Thanks!

**Comment by melhorAmigolegal** [comment]
> 

Ah ok, Vanced team does not work on YT Music anymore?
