### ISSUE TITLE
[Bug] YouTube Vanced open crash 

### ISSUE THREAD

**Issue by melhorAmigolegal** [TeamVanced/Vanced#1813]
**Bug description:**
Open doesn't open, appears that YouTube Vanced is showing several errors 

**Does your issue exists in the vanced guides? (YES/No)**
No

**Variant:**
Root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
youtubevanced.com

**Android version:**
Android 10

**Device:**
Motorola Moto G7 Play (channel)

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app

**Expected behaviour:**
Has to open, but didn't open

**Screen recording/screenshot of the bug:**

https://www.mediafire.com/file/x4knb4qci5yy5r0/vidma_recorder_03042023_181534.mp4/file

_Attach logcats in case of crashes by uploading them to pastebin or katbin if possible. These can help solve the issue._

**Comment by milindgoel15** [comment]
Closing issue because used downloaded from a fake website. Also, Please read the readme of this repository.
