### ISSUE TITLE
Error upon watching a video

### ISSUE THREAD

**Issue by L8NIKC** [TeamVanced/Vanced#1814]
![Screenshot_20230411_064504_com vanced android youtube](https://user-images.githubusercontent.com/122442274/231013517-62d0ac6d-6cae-44b7-b120-8001d46f161f.jpg)
It keeps saying that i need the latest version i have re installed YouTube vanced about 15 times no shit it won't let me watcb videos only shorts for some odd fckin reason bruh i cant even fucking play any video even fking live streams i can i just fking cant
![Screenshot_20230411_065103_com vanced android youtube](https://user-images.githubusercontent.com/122442274/231013817-6b301651-b96e-40e0-85b2-3306cd7621ef.jpg)
![Screenshot_20230411_065059_com vanced android youtube](https://user-images.githubusercontent.com/122442274/231013827-6ee5d1d7-0865-4691-882d-3326659eecaf.jpg)
![Screenshot_20230411_065047_com vanced android youtube](https://user-images.githubusercontent.com/122442274/231013841-6df60ffc-53b7-4c2a-83bc-7db8e229dacb.jpg)

**Comment by milindgoel15** [comment]
READ THE README OF THIS REPOSITORY.

**Comment by LosGabrielos** [comment]
Same here... Why is that so

**Comment by ChaosNicro** [comment]
Vanced is dead. Migrate to one of the forks (revanced) if you need the ability to post comments or a recommended page. Otherwise give newpipe a try, i can recommend it. Piped and libretube offer a compromise between both.

**Comment by AsparagusEduardo** [comment]
> Fork
👀👀👀👀👀👀👀
