### ISSUE TITLE
[Bug] No Videos Loading

### ISSUE THREAD

**Issue by AlexTheOutsider22** [TeamVanced/Vanced#1817]
**Bug description:**
Any and all videos do not load, it just tells me to use the most recent version of YouTube, and I'm using the most recent version of Vanced and MicroG

**Does your issue exists in the vanced guides? (YES/No)**
I haven't noticed them, but I'm pretty sure it's not there

**Variant:**
Non-root

**Vanced version:**
v17.03.38

**Link used to download vanced:**
I can't remember, I have used it fine for over a year

**Android version:**
Android 11 

**Device:**
Redmi Note 8T

**Steps to Reproduce:**
Steps to reproduce the error:
1. Open the app
2. Open a video
3. doesn't load

**Expected behaviour:**
Open a video

**Screen recording/screenshot of the bug:**
![Screenshot_2023-04-19-23-23-23-917_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/103733984/233193337-79b94952-1f2a-4d94-b8dc-8d1868170d84.jpg)

_Attach logcats in case of crashes by uploading them to pastebin or katbin if possible. These can help solve the issue._

**Comment by RevoSucks** [comment]
Same

**Comment by Feelf4n** [comment]
Anything new??

**Comment by olo66641** [comment]
Nope, the Bug IS still there

**Comment by AlcuZan** [comment]
And it will NOT be fixed. What part of "this app is discontinued" don't you people understand? Look for an alternative. LibreTube is good

**Comment by crewockeez** [comment]
Same

**Comment by Alexisvri** [comment]
It's good for me, so no, the app is not discontinued... I don't see an official message of this info...

**Comment by AlcuZan** [comment]
For fucks sake. It's it so hard to read the fucking README? Yes, it IS discontinued and you denying that doesn't change fuck about that

**Comment by AlcuZan** [comment]
https://github.com/TeamVanced/Vanced

Go ahead and read the fucking README! It's not that hard!

**Comment by Alexisvri** [comment]
why are you talking like that ? It work for me now, no more bugs... sooo...

**Comment by AlcuZan** [comment]
Because idiots make me angry. So many issues here all asking the same thing because people are too stupid to read the fucking README. It works for you NOW, but that will change soon. The app is discontinued. It will stop working for everyone eventually. Whether you want to believe that or not.

**Comment by Feelf4n** [comment]
I for one know that it but thought that maybe someone had had the issue and solved it in some way. This was just to ask in general, not for the developers or anything like that. But in good news it’s working right 🤩🤩

**Comment by milindgoel15** [comment]
@AlcuZan calm down
