### ISSUE TITLE
[Bug] Deleting error



### ISSUE THREAD

**Issue by GitHubIXChara** [TeamVanced/Vanced#1820]
**I know that i shouldn't create the issue, but this is really important, as addition, it is being in custom Rom crDroid**

**Bug description:**
After deleting Vanced MUSIC after reboot it coming back, magisk showing that is doing service.d

**Does your issue exists in the vanced guides? (YES/No)**
No

**Variant:**
root

**Vanced version:**
Latest

**Link used to download vanced**
https://youtubevanced.com

**Android version:**
Android 11 

**Device:**
Redmi 8

**Steps to Reproduce:**
Steps to reproduce the error:
1. Long click app icon
2. Click on 'Delete'
3. Confirm deletion
4. reboot
5. notice that music vanced got back

**Expected behaviour:**
YTVanced MUSIC should be deleted instead of appearing in the system as Working app

**Screen recording/screenshot of the bug:**
Cannot record video what will show that after reboot

Log cat:
[Screenshot_20230430-225316553_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/121542701/235373625-fb46b6ab-119a-4676-9f60-c3b1828cfd9d.jpg)

**Comment by milindgoel15** [comment]
The link you used is not official source of download. The only official links were vancedapp.com

We don't know what your installation did to your system. You can try using the vanced manager to uninstall.

**Comment by GitHubIXChara** [comment]
> The link you used is not official source of download. The only official links were vancedapp.com
> 
> We don't know what your installation did to your system. You can try using the vanced manager to uninstall.

i have tried to check the code of youtubevanced.com's app and asked friends to send the vanced manager from vancedapp.com. the code didnt changed at all. the thing i noticed is that it have added new service, where it is located in the standart app?

**Comment by GitHubIXChara** [comment]
anyway, i've shoulded to reflash my os, the problem fixed, no yt music. the vanced was a really cool project, this is really sad that theres no way to make it alive again, this is best yt mod i've ever seen.
