### ISSUE TITLE
[Question] PLEASE IMPLEMENT the option to remove YouTube Shorts section 

### ISSUE THREAD

**Issue by Bilots00** [TeamVanced/Vanced#1823]
**Description**
I want the possibility to remove "Shorts" section and replace It with the old "Trends/Tendency". I tryed to download the oldest Vanced version and 1 month ago it worked perfectly with no problems but now It doesn't work (server issue 400) so i am obliged to update vanced to the latest version where there are the YouTube Shorts that I hate.. if you put the option to remove Shorts from the settings that would be great! Thanks

_Attach images/videos if possible. These can be helpful in figuring out what the question is about._

**Comment by milindgoel15** [comment]
You are out of your mind or what?

**Comment by Bilots00** [comment]
> You are out of your mind or what?


Coming from you, it's funny enough that you're not able to give an exhaustive and complete answer. It's funny enough

**Comment by milindgoel15** [comment]
> > You are out of your mind or what?
> 
> Coming from you, that you're not able to give an exhaustive and complete answer..It's funny enough

Says the one who created 4 duplicate issues instead of actually opening your eyes and reading the readme section of this repository

![image](https://github.com/TeamVanced/Vanced/assets/45682747/92c42bfa-7dca-440e-9ef2-89acc0b8d083)

**Comment by Bilots00** [comment]
> > > You are out of your mind or what?
> > 
> > 
> > Coming from you, that you're not able to give an exhaustive and complete answer..It's funny enough
> 
> Says the one who created 4 duplicate issues instead of actually opening your eyes and reading the readme section of this repository
> 
> ![image](https://user-images.githubusercontent.com/45682747/239740672-92c42bfa-7dca-440e-9ef2-89acc0b8d083.png)

said the one who is not capable of giving a pertinent answer to my question... if I duplicated 4 the problem is perhaps because the answer you gave me has absolutely nothing to do with what I asked you... if you still don't understand tell me and I'll explain it to you with a little drawing so maybe you wake up! other than opening your eyes, you should really change jobs that customer support is not your thing

**Comment by milindgoel15** [comment]
So funny bro 😂😂😂

Good luck with that

**Comment by Bilots00** [comment]
ok phenomenon, thanks for your precious contribution👍🏼😂
I would never have done it without you 🤣🤣🤣🤣
